export enum Subject {
  PROGRAMMING = 'PROGRAMMING',
  MATHEMATICS = 'MATHEMATICS',
  HISTORY = 'HISTORY',
  SCIENCE = 'SCIENCE',
  LANGUAGE = 'LANGUAGE',
  GEOGRAPHY = 'GEOGRAPHY',
  ARTS = 'ARTS',
  SPORTS = 'SPORTS',
  MUSIC = 'MUSIC',
  GENERAL = 'GENERAL'
}